--对O1,O2,D1,D2的稳定性系数进行调整,根据数据我发现存在一些车辆的稳定性系数大于1,
--这是由于有一些卡口会拍到同时几个车道的车辆,这导致同一个位置被重复相加了,但是这种情况很少,
--O1O2D1D2中最多只有30多辆车,因此将这些车辆的稳定性系数直接设为1.

UPDATE STABLE_RATIO_O1_NEW
SET STABLE_RATIO = 1
WHERE STABLE_RATIO > 1;

UPDATE STABLE_RATIO_O2_NEW
SET STABLE_RATIO = 1
WHERE STABLE_RATIO > 1;

UPDATE STABLE_RATIO_D1_NEW
SET STABLE_RATIO = 1
WHERE STABLE_RATIO > 1;

UPDATE STABLE_RATIO_D2_NEW
SET STABLE_RATIO = 1
WHERE STABLE_RATIO > 1;