--将之前生成的各个聚类指标的table做表联结,形成最终的透视表.(各个聚类指标均没有进行处理,直接作为聚类的feature)
CREATE TABLE COMMUVEHFEAT
AS (
SELECT * 
from
( -- 所有通勤指标联结后的透视表
select WORKDAY_PEAKHOUR_FREQ.CAR_NUM , WORKDAY_PEAKHOUR_FREQ.FM_RATIO AS F1 , 
    WORKDAY_TRA_FREQ.FM_RATIO AS F2 , STABLE_RATIO_O1_NEW.STABLE_RATIO AS O1 , 
    STABLE_RATIO_D1_NEW.STABLE_RATIO AS D1 , STABLE_RATIO_O2_NEW.STABLE_RATIO AS O2 , 
    STABLE_RATIO_D2_NEW.STABLE_RATIO AS D2 , OD_SPATIAL_STABLE_RATIO.FS , 
    WORKDAY_OFFPEAK_STD_AND_AVG.STD_FD , WORKDAY_OFFPEAK_STD_AND_AVG.AVG_FD
from ((((((WORKDAY_PEAKHOUR_FREQ
INNER JOIN
WORKDAY_TRA_FREQ
on WORKDAY_PEAKHOUR_FREQ.CAR_NUM = WORKDAY_TRA_FREQ.CAR_NUM)
INNER JOIN
STABLE_RATIO_O1_NEW
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = STABLE_RATIO_O1_NEW.CAR_NUM)
INNER JOIN STABLE_RATIO_D1_NEW
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = STABLE_RATIO_D1_NEW.CAR_NUM)
INNER JOIN STABLE_RATIO_O2_NEW
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = STABLE_RATIO_O2_NEW.CAR_NUM)
INNER JOIN STABLE_RATIO_D2_NEW
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = STABLE_RATIO_D2_NEW.CAR_NUM)
INNER JOIN OD_SPATIAL_STABLE_RATIO
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = OD_SPATIAL_STABLE_RATIO.CAR_NUM)
LEFT OUTER JOIN WORKDAY_OFFPEAK_STD_AND_AVG
ON WORKDAY_PEAKHOUR_FREQ.CAR_NUM = WORKDAY_OFFPEAK_STD_AND_AVG.CAR_NUM
) FEATTABLE
WHERE FS IS NOT NULL
)


--将上述生成的透视表中的STD_FD和AVG_FD两个指标进行缺失值填补
--AVG_FD为NULL的填补为0,因为这说明车辆在平峰时段没有被检测到.
update COMMUVEHFEAT
    set AVG_FD = 0
where AVG_FD IS NULL ; 
--STD_FD为NULL的填补为0,因为这说明车辆在平峰时段没有出行,也就是说出行非常规律.
update COMMUVEHFEAT
    set STD_FD = 0
where STD_FD IS NULL ; 
